language: php
php:
  - 7.1
before_script:
  - composer install
  - composer dump-autoload
  - cp .env.travis .env
  - php artisan jwt:generate
  - php artisan key:generate
  - php artisan vendor:publish
script: phpunit